# Generado automáticamente — 2026-03-06 12:50
# 50 pares con vol>$500,000 y spread<1.5%
# Ordenados por volumen 24h descendente

PARES = [
    "BTC-USDT",
    "NCCOGOLD2USD-USDT",
    "ETH-USDT",
    "SOL-USDT",
    "NCCOOILWTI2USD-USDT",
    "BOME-USDT",
    "NCCOXAG2USD-USDT",
    "IMX-USDT",
    "AVAX-USDT",
    "XRP-USDT",
    "DOGE-USDT",
    "SUI-USDT",
    "SAGA-USDT",
    "NCCOOILBRENT2USD-USDT",
    "COMP-USDT",
    "ETHFI-USDT",
    "ARPA-USDT",
    "DOT-USDT",
    "NCSINASDAQ1002USD-USDT",
    "JASMY-USDT",
    "LINK-USDT",
    "AAVE-USDT",
    "XAUT-USDT",
    "NCSISP5002USD-USDT",
    "HYPE-USDT",
    "BLUR-USDT",
    "ARB-USDT",
    "RIVER-USDT",
    "SEI-USDT",
    "RARE-USDT",
    "OKB-USDT",
    "BARD-USDT",
    "NCSINIKKEI2252USD-USDT",
    "SHIB-USDT",
    "ATOM-USDT",
    "BNB-USDT",
    "STX-USDT",
    "NEAR-USDT",
    "ADA-USDT",
    "SIGN-USDT",
    "HUMA-USDT",
    "ASTER-USDT",
    "NCSIDOWJONES2USD-USDT",
    "PAXG-USDT",
    "NCCOGASOLINE2USD-USDT",
    "H-USDT",
    "LTC-USDT",
    "ZEC-USDT",
    "ZRO-USDT",
    "KITE-USDT"
]
