FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY *.py ./
RUN mkdir -p logs

# ── Variables de entorno (Railway → sobreescribir) ──────────────────
ENV PORT=8080
ENV SCAN_INTERVAL_SEC=60
ENV KLINE_INTERVAL=1h

# Señales — más permisivos que v4
ENV MA_FAST=9
ENV MA_SLOW=21
ENV PROJ_LENGTH=10
ENV MIN_MEAN_PNL=0.0005
ENV MIN_SIGNAL_SCORE=40
ENV SIGNAL_LOOKBACK=3
ENV MIN_SIGNALS_HIST=1

# Filtros graduales (no duros)
ENV USE_OB_FILTER=true
ENV USE_OB_SCAN=true
ENV USE_OI_FILTER=true
ENV USE_TREND_FILTER=true
ENV TREND_INTERVAL=4h

# Scanner
ENV TOP_SYMBOLS=30
ENV MIN_VOLUME_USDT=500000
ENV VOL_SPIKE_MIN=2.0
ENV MOMENTUM_MIN=1.5

# Indicadores
ENV RSI_PERIOD=14
ENV RSI_OB=70
ENV RSI_OS=30
ENV ADX_PERIOD=14
ENV BB_PERIOD=20
ENV BB_MULT=2.0
ENV TP_RR=2.0
ENV SL_ATR_MULT=1.5

# Order book
ENV BOOK_DEPTH=50
ENV WALL_MULT=3.0
ENV DEPTH_RANGE=0.02

# Trading
ENV LEVERAGE=5
ENV RISK_PCT=0.01
ENV MAX_OPEN_TRADES=5
ENV MAX_HOLD_HOURS=48
ENV MIN_NOTIONAL=10
ENV MAX_POSITION_SIZE=200
ENV MAX_DAILY_TRADES=10
ENV MIN_RR=1.2
ENV TP1_PCT=0.60
ENV DRY_RUN=false
ENV AUTO_TRADING_ENABLED=true

# Risk
ENV MAX_DAILY_DRAWDOWN=0.05
ENV MAX_PORTFOLIO_HEAT=0.15
ENV MAX_CONSEC_LOSSES=4
ENV MAX_PER_GROUP=2

EXPOSE 8080
CMD ["python", "bot.py"]
